databases = [
  {
    provider = elasticsearch
    host = slave.tooo.top
    index = area
    port = 9200
    user = "ENC:6ue9ugmDYqB0WvHQQHDuqlsliWSA13gZ3UTwJxW+GY4="
    password = "ENC:qw4+6BQHhH2JXonrnOwObTnrXxz8l/cUIvoyz91ZbM4="
    connectTimeout = 5000
    socketTimeout = 10000
  }
]