databases = [
  {
    provider = elasticsearch
    host = slave.tooo.top
    index = area
    port = 9201
    user = "ENC:dvRHEtU9mLb+Rsz5/USWvfMFLXJUR5MkgvR9cjqy4RY="
    password = "ENC:/0vQ+ChDGf5sIfoBxmm3L1At1JEoducF6SWIJ1Ht+vY="
    #port = 9200
    #user = "ENC:chjW/08flC6ibxj6ksIkrw80ly4Ul8qagR+tsZwzu9g="
    #password = "ENC:VfGAgwxqcPuiUiKnqxQtM2Ajcs/ICBSBEClJp619sIY="
    #user = elastic
    #password = Qwe123465
    connectTimeout = 5000
    socketTimeout = 10000
  }
]