[
    {
    type = read
    provider = psql
    host = slave.tooo.top
    port = 6543
    user = "ENC:dEhhMWGDj1k24bGyW2vdErkeSA96eR7Mgmz8hiGXaPk="
    password = "ENC:Nmwg38OLcnE8MdRNJDcx7v6cXsFs81sISdLJAYX+5Gc="
    hikari = {
      dataSourceClassName = org.postgresql.ds.PGSimpleDataSource
      maximumPoolSize = 9
    }
  },
  ｛
      type = read
      provider = elasticsearch
      host = slave.tooo.top
      port = 9200
      user = "ENC:6ue9ugmDYqB0WvHQQHDuqlsliWSA13gZ3UTwJxW+GY4="
      password = "ENC:qw4+6BQHhH2JXonrnOwObTnrXxz8l/cUIvoyz91ZbM4="
    }
]